# Generated by Django 6.0 on 2025-12-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('team_member', 'Team Member'), ('viewer', 'Viewer'), ('recruitment_agent', 'Recruitment Agent')], default='team_member', max_length=20),
        ),
    ]
