# Generated by Django 4.2.7 on 2026-01-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20260124_0055'),
        ('core', '0031_merge_20260124_1626'),
    ]

    operations = [
    ]
