# Generated by Django 4.2.7 on 2026-01-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20260127_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by_company_user',
            field=models.ForeignKey(blank=True, help_text='Company user who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='core.companyuser'),
        ),
    ]
