# Generated by Django 4.2.7 on 2026-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_created_by_company_user_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('team_member', 'Team Member'), ('developer', 'Developer'), ('viewer', 'Viewer'), ('internee', 'Internee'), ('designer', 'Designer')], default='team_member', max_length=20),
        ),
    ]
