# Generated by Django 6.0 on 2025-12-21 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512)),
                ('parsed_json', models.TextField(help_text='Structured CV data from CVParserAgent')),
                ('insights_json', models.TextField(blank=True, help_text='Summarization results from SummarizationAgent', null=True)),
                ('role_fit_score', models.IntegerField(blank=True, help_text='Role fit score 0-100', null=True)),
                ('rank', models.IntegerField(blank=True, help_text='Final ranking position', null=True)),
                ('enriched_json', models.TextField(blank=True, help_text='Enrichment results from LeadResearchEnrichmentAgent', null=True)),
                ('qualification_json', models.TextField(blank=True, help_text='Qualification results from LeadQualificationAgent', null=True)),
                ('qualification_decision', models.CharField(blank=True, help_text='INTERVIEW/HOLD/REJECT', max_length=32, null=True)),
                ('qualification_confidence', models.IntegerField(blank=True, help_text='Confidence score 0-100', null=True)),
                ('qualification_priority', models.CharField(blank=True, help_text='HIGH/MEDIUM/LOW', max_length=16, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'CV Record',
                'verbose_name_plural': 'CV Records',
                'db_table': 'ppp_cv_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
