# Generated by Django 5.0.1 on 2025-12-23 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('job_role', models.CharField(max_length=255)),
                ('interview_type', models.CharField(choices=[('ONLINE', 'Online'), ('ONSITE', 'Onsite')], default='ONLINE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Awaiting candidate response'), ('SCHEDULED', 'Scheduled - Interview confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('selected_slot', models.CharField(blank=True, help_text='The time slot selected by candidate', max_length=255, null=True)),
                ('available_slots_json', models.TextField(help_text='JSON array of available time slots offered to candidate')),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cv_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='recruitment_agent.cvrecord')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_datetime'], name='recruitment_status_210d1e_idx'), models.Index(fields=['candidate_email'], name='recruitment_candida_1c227e_idx')],
            },
        ),
    ]
