# Generated by Django 5.0.1 on 2025-12-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0002_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='confirmation_token',
            field=models.CharField(blank=True, help_text='Unique token for candidate slot selection', max_length=64, null=True, unique=True),
        ),
    ]
