"""
Django settings for project_manager_ai project.
Generated by 'django-admin startproject' using Django 5.0.1.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-9hce6%w7!*)lb#$^6)gb8!h01#6t6y_85nn=exz82l4dj=6q45'
DEBUG = True
ALLOWED_HOSTS = []


# --------------------
# Applications
# --------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'project_manager_agent',
    'recruitment_agent',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_manager_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_manager_ai.wsgi.application'


# --------------------
# Database (SQL Server Express)
# --------------------
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DB_NAME', 'project_manager_db'),
        'HOST': r'DESKTOP-279M6LJ\SQLEXPRESS',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
        },
    }
}

# ⚠️ Notes:
# - No PORT (SQL Express uses dynamic ports)
# - No USER / PASSWORD (Windows Authentication)
# - No extra_params (causes invalid connection string errors)


# --------------------
# Password validation
# --------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------
# Internationalization
# --------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --------------------
# Static files
# --------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# --------------------
# Default PK
# --------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------
# Auth redirects
# --------------------
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'


# --------------------
# AI / API Settings
# --------------------
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
GROQ_MODEL = os.getenv('GROQ_MODEL', 'llama-3.1-8b-instant')
GROQ_REC_API_KEY = os.getenv('GROQ_REC_API_KEY', '')


# --------------------
# Email Configuration
# --------------------
# Check EMAIL_BACKEND from .env (remove quotes if present)
email_backend_env = os.getenv('EMAIL_BACKEND', '').strip().strip("'\"")
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').strip()

# Check if SMTP is requested (either full path or 'smtp' keyword)
if email_backend_env and ('smtp' in email_backend_env.lower() or 'EmailBackend' in email_backend_env):
    # SMTP Configuration for actual email sending
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com').strip()
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower().strip() == 'true'
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower().strip() == 'true'
    
    # Verify SMTP settings are configured
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        print("\n" + "="*60)
        print("WARNING: SMTP backend requested but EMAIL_HOST_USER or EMAIL_HOST_PASSWORD not set!")
        print("Falling back to console backend (emails will print to terminal)")
        print("="*60 + "\n")
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    else:
        print("\n" + "="*60)
        print("EMAIL CONFIGURATION:")
        print(f"  Backend: SMTP")
        print(f"  Host: {EMAIL_HOST}")
        print(f"  Port: {EMAIL_PORT}")
        print(f"  From: {EMAIL_HOST_USER}")
        print("="*60 + "\n")
else:
    # Console backend (for development - emails print to terminal)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("\n" + "="*60)
    print("INFO: Using console email backend (emails will print to terminal)")
    print("To send actual emails, set in .env:")
    print("  EMAIL_BACKEND=smtp")
    print("  EMAIL_HOST_USER=your-email@gmail.com")
    print("  EMAIL_HOST_PASSWORD=your-app-password")
    print("="*60 + "\n")

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@example.com').strip()
RECRUITER_EMAIL = os.getenv('RECRUITER_EMAIL', '').strip()
